// Code generated by Design interface, manipulated by Trevor Walden
namespace HUDEditor
{
    partial class Form1
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.HUD_View = new System.Windows.Forms.GroupBox();
            this.CreateElement = new System.Windows.Forms.Button();
            this.editLabel = new System.Windows.Forms.Label();
            this.SuspendLayout();
            // 
            // HUD_View
            // 
            this.HUD_View.Location = new System.Drawing.Point(7, 59);
            this.HUD_View.Name = "HUD_View";
            this.HUD_View.Size = new System.Drawing.Size(1280, 720);
            this.HUD_View.TabIndex = 0;
            this.HUD_View.TabStop = false;
            this.HUD_View.Text = "HUD View";
            this.HUD_View.Enter += new System.EventHandler(this.groupBox1_Enter);
            // 
            // CreateElement
            // 
            this.CreateElement.Location = new System.Drawing.Point(15, 21);
            this.CreateElement.Name = "CreateElement";
            this.CreateElement.Size = new System.Drawing.Size(121, 26);
            this.CreateElement.TabIndex = 1;
            this.CreateElement.Text = "Create Element";
            this.CreateElement.UseVisualStyleBackColor = true;
            this.CreateElement.Click += new System.EventHandler(this.CreateElement_Click);
            // 
            // editLabel
            // 
            this.editLabel.AutoSize = true;
            this.editLabel.Location = new System.Drawing.Point(500, 26);
            this.editLabel.Name = "editLabel";
            this.editLabel.Size = new System.Drawing.Size(105, 17);
            this.editLabel.TabIndex = 2;
            this.editLabel.Text = "Edit Element ():";
            // 
            // Form1
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 16F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1289, 781);
            this.Controls.Add(this.editLabel);
            this.Controls.Add(this.CreateElement);
            this.Controls.Add(this.HUD_View);
            this.Name = "Form1";
            this.Text = "Form1";
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.GroupBox HUD_View;
        private System.Windows.Forms.Button CreateElement;
        private System.Windows.Forms.Label editLabel;
    }
}

